/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mtbs;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author kjha4
 */
public class RequestBroker extends javax.swing.JFrame {
    
    String[] strArray = {"Marketprice", "Limit", "Stop-Limit", "Stop"};
    /**
     * Creates new form RequestBroker
     */
    public RequestBroker() {
        initComponents();
        fillCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCompany = new javax.swing.JLabel();
        labelQuantity = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        labelOrderType = new javax.swing.JLabel();
        txtOrderType = new javax.swing.JComboBox();
        buttonOrderTrader = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelCompany.setText("Company");

        labelQuantity.setText("Quantity");

        labelOrderType.setText("Order Type");

        txtOrderType.setModel(new javax.swing.DefaultComboBoxModel(new String[] {""}));
        txtOrderType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderTypeActionPerformed(evt);
            }
        });

        buttonOrderTrader.setText("Order Trader");
        buttonOrderTrader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrderTraderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelOrderType)
                    .addComponent(labelQuantity)
                    .addComponent(labelCompany))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonOrderTrader, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCompanyName)
                        .addComponent(txtQuantity)
                        .addComponent(txtOrderType, 0, 106, Short.MAX_VALUE)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCompany)
                    .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelQuantity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelOrderType)
                    .addComponent(txtOrderType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(buttonOrderTrader)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOrderTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderTypeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtOrderTypeActionPerformed

    private void buttonOrderTraderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrderTraderActionPerformed
        // TODO add your handling code here:
        String companyName = txtCompanyName.getText();
        String quantity = txtQuantity.getText();
        String orderType = txtOrderType.getSelectedItem().toString();

        JOptionPane.showMessageDialog(this, companyName + " " + quantity + " " + orderType);
    }//GEN-LAST:event_buttonOrderTraderActionPerformed
    
    
    private void fillCombo(){
        for(String str : strArray){
            txtOrderType.addItem(str);
            txtOrderType.setSelectedIndex(1);
            txtOrderType.setEditable(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RequestBroker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RequestBroker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RequestBroker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RequestBroker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RequestBroker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOrderTrader;
    private javax.swing.JLabel labelCompany;
    private javax.swing.JLabel labelOrderType;
    private javax.swing.JLabel labelQuantity;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JComboBox txtOrderType;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
